version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
         command: nuget.exe restore windows-runtime\windows-runtime.sln
         shell: cmd.exe
      - run:
         command: MSBuild.exe -p:Configuration=Release -p:Platform=x64 windows-runtime\windows-runtime\windows-runtime.vcxproj
         shell: cmd.exe
      - run:
         command: windows-runtime\Release\windows-runtime-test.exe
         shell: cmd.exe
