version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
         command: nuget.exe restore windows\game-engine.sln
         shell: cmd.exe
      - run:
         command: MSBuild.exe -p:Configuration=Release -p:Platform=x64 windows\game-engine\game-engine.vcxproj
         shell: cmd.exe